In [3]:
import pymongo
import operator
import numpy as np
from pymongo import MongoClient

In [4]:
client = MongoClient('localhost', 27017)
db = client.nesoi
terrain = db.terrain

In [39]:
def createCType():
    c = set()
    for cell in terrain.find():
        c.add(cell["terrain"])

    tmp = list(c)
    
    return sorted(tmp)

In [ ]:
CType = createCType()

In [36]:
def cTypeToIdx(val):
    return Ctype.index(val)

In [542]:
def getCellIdxTerrainDistribution(idx, threshold, show):

    results = list()
    for cell in terrain.find({"idx":idx}):
        results.append(cell["terrain"])
    
    uniqueItems = set(results)

    totalLen = float(len(results))
    
    d = {}
    for item in uniqueItems:
        percent = 100*results.count(item) / totalLen
        d[item] = percent

    sorted_x = sorted(d.items(), key=operator.itemgetter(1), reverse=True)
    if show:
        sorted_x = getThreshold(sorted_x, threshold)
    
    return sorted_x

In [19]:
def getThreshold(d, threshold):
    
    accum = 0
    terrains = ()
    cells = {}
    for ter, per in d:
        cells[ter] = per

        accum = accum + per  

        if accum > threshold:
            break

    for key in cells:
        cells[key] = cells[key] / accum
    
    sorted_x = sorted(cells.items(), key=operator.itemgetter(1), reverse=True) 
    return sorted_x

In [42]:
def getDistribution(idx):
    results = list()
    for cell in terrain.find({"idx":idx}):
        results.append(cell["terrain"])

    uniqueItems = set(results)
    totalLen = float(len(results))
    d = {}
    for item in uniqueItems:
        percent = 100*results.count(item) / totalLen
        d[item] = percent
    return sorted(d.items(), key=operator.itemgetter(1), reverse=True)
    


In [45]:
print getDistribution(0)
for t,p in getDistribution(0):
    print cTypeToIdx(t), p

[(u'mountainRed', 50.78125), (u'bushGreen', 14.0625), (u'mountainGreen', 10.9375), (u'bushRed', 7.8125), (u'mountainWhite', 6.25), (u'waterRed', 5.46875), (u'waterGreen', 4.6875)]
82 50.78125
58 14.0625
2 10.9375
31 7.8125
15 6.25
34 5.46875
49 4.6875


In [21]:
d = getCellIdxTerrainDistribution(0, 70, True)

for label, val in d:
    print label + '\t' + str(val)

mountainRed	0.670103092784
bushGreen	0.185567010309
mountainGreen	0.144329896907


In [22]:
def generateCss(idx, threshold):
    
    print ".content div:nth-child(" + str(idx + 1) + ")" + ".t" + str(threshold) + " {animation-name: bg" + str(idx) + "-t" + str(threshold) + ";}"

    curPercent = 0
    firstTerrain = ""

    css = "@keyframes bg" + str(idx) + "-t" + str(threshold) + " {"
    
    d = getCellIdxTerrainDistribution(idx, threshold, True)

    for ter, per in d:
        
        per = per * 100

        if not firstTerrain:
            firstTerrain = ter
            css = css + "0% {background-image: url('img/" + ter + ".png');}"
            css = css + "{0:.0f}".format(per/ 2) + "% {background-image: url('img/" + ter + ".png');}"
        else:
            css = css + "{0:.0f}".format(curPercent) + "% {background-image: url('img/" + ter + ".png');}"
            
        curPercent = curPercent + per

    css = css + "100% {background-image: url('img/" + firstTerrain + ".png');}}"

    print css

In [94]:
for i in range(0,1):
    generateCss(i, 100)
    generateCss(i, 90)
    generateCss(i, 80)
    generateCss(i, 70)
    generateCss(i, 60)
    generateCss(i, 50)
    generateCss(i, 50)
    generateCss(i, 40)
    generateCss(i, 30)
    generateCss(i, 20)
    generateCss(i, 10)
    

.content div:nth-child(1).t100 {animation-name: bg0-t100;}
@keyframes bg0-t100 {0% {background-image: url('img/mountainRed.png');}25% {background-image: url('img/mountainRed.png');}51% {background-image: url('img/bushGreen.png');}65% {background-image: url('img/mountainGreen.png');}76% {background-image: url('img/bushRed.png');}84% {background-image: url('img/mountainWhite.png');}90% {background-image: url('img/waterRed.png');}95% {background-image: url('img/waterGreen.png');}100% {background-image: url('img/mountainRed.png');}}
.content div:nth-child(1).t90 {animation-name: bg0-t90;}
@keyframes bg0-t90 {0% {background-image: url('img/mountainRed.png');}27% {background-image: url('img/mountainRed.png');}53% {background-image: url('img/bushGreen.png');}68% {background-image: url('img/mountainGreen.png');}80% {background-image: url('img/bushRed.png');}88% {background-image: url('img/mountainWhite.png');}94% {background-image: url('img/waterRed.png');}100% {background-image: url('img/moun

In [348]:
# # Look at the pair combinatons 
# def getPairs():
#     pairs = list()
#     for cell in terrain.find({"idx":0}):

#         x = cell["x"]
#         y = cell["y"] 

#         pair = [(x, y, cell["terrain"])]

#         for neighbor in terrain.find({"x":x + 1, "y": y}):
#             pair.append((neighbor["x"], neighbor["y"], neighbor["terrain"]))

#         pairs.append(pair)
        
#     return pairs

In [349]:
# pairs = getPairs();
# pairs

In [350]:
# # d={'a':[],'b':[]}
# d={}
# for p in pairs:
 
#     if(not p[0][2] in d.keys()):
#         d[p[0][2]] = list()

#     d[p[0][2]].append(p[1][2])

In [351]:
# d

In [39]:
# terra = list()
# total = 0
# for i in d:
#     cellTerrainItemCount = {}
   
#     for j in d[i]:
       
#         if(not j in cellTerrainItemCount.keys()):
#             cellTerrainItemCount[j] = 0
        
#         cellTerrainItemCount[j] += 1
       
     
#     terra.append((i, cellTerrainItemCount))
    

In [352]:
# terra


# Helper Functions

In [383]:
def idxToCoord(idx): 
    x = idx % 16
    y = idx / 16
    return x, y  

In [526]:
def removeZeroColumnsRows(matrix):
    
    if isinstance(matrix, np.matrix) :
        rows = (matrix).any(axis=1)
        nx = matrix[rows.A1]
        cols = (matrix).any(axis=0)
        ny = nx[:,cols.A1]
    elif isinstance(matrix, np.ndarray) :
        # Remove any zero rows
        nx = matrix[(matrix).any(axis=1)]
        ny = nx[:,(nx).any(axis=0)]
    else:
        ny = np.zeros(len(matrix))
        
    return ny

# Conditional Probability Distribution 

The goal is to predict what the Cell terrain will be in index 1 given the value in index 0. 

`P(Y | X)`. Where `X` = Cell index 0 and `Y` = Cell index 1

\begin{equation*}
P(Y|X) = P(X) * P(Y | X)
\end{equation*}

In [385]:
def createObservationDisribution(idx1, idx2):
    
    od = np.zeros([len(Ctype),len(Ctype)])
    
    for cell in terrain.find({"idx":idx1}):

        x = cell["x"]
        y = cell["y"] 
        
        delX, delY = idxToCoord(idx2)
        
        neighbor = terrain.find_one({"x":x + delX, "y":y + delY})
        
        Xi = cTypeToIdx(cell["terrain"])            
        Yi = cTypeToIdx(neighbor["terrain"])
            
        od[Xi, Yi] += 1
            
    return od

In [489]:
od = createObservationDisribution(0,1)

In [527]:
print removeZeroColumnsRows(od)

[[ 14.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   8.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   4.   0.   0.   3.]
 [  0.   0.   0.   0.   0.   0.   6.   0.   0.]
 [  0.   0.   0.   0.   3.   0.   0.  15.   0.]
 [  0.   0.   1.   0.   0.   0.   0.   0.  64.]]


In [347]:
def validateObservedResults(od):
    # Validate expected counts

    print od[cTypeToIdx('mountainGreen'),cTypeToIdx('mountainGreen')] == 14
    print od[cTypeToIdx('waterGreen'),cTypeToIdx('waterGreen')] == 6
    print od[cTypeToIdx('waterRed'),cTypeToIdx('waterRed')] == 4
    print od[cTypeToIdx('waterRed'), cTypeToIdx('mountainRed')] == 3
    print od[cTypeToIdx('mountainWhite'),cTypeToIdx('mountainWhite')] == 8
    print od[cTypeToIdx('mountainRed'),cTypeToIdx('mountainRed')] == 64
    print od[cTypeToIdx('mountainRed'), cTypeToIdx('sand')] == 1
    print od[cTypeToIdx('bushRed'),cTypeToIdx('bushRed')] == 10
    print od[cTypeToIdx('bushGreen'), cTypeToIdx('bushGreen')] == 15
    print od[cTypeToIdx('bushGreen'),cTypeToIdx('dirt')] == 3
    print od.sum() == 128

validateObservedResults(od)

True
True
True
True
True
True
True
True
True
True
True


In [483]:
def createCpd(observedDistribution):
    rowSum = np.sum(observedDistribution,1) + 0.0000000001
    cpd = np.divide(observedDistribution, np.matrix(rowSum).T)[:None]
    return cpd

In [484]:
cpd = createCpd(od)

In [532]:
smallCpd = removeZeroColumnsRows(np.around(cpd, decimals=3))
print smallCpd

[[ 1.     0.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     1.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.571  0.     0.     0.429]
 [ 0.     0.     0.     0.     0.     0.     1.     0.     0.   ]
 [ 0.     0.     0.     0.     0.167  0.     0.     0.833  0.   ]
 [ 0.     0.     0.015  0.     0.     0.     0.     0.     0.985]]


In [567]:
marginal

array([  0.     ,   0.     ,  10.9375 ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   6.25   ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   7.8125 ,   0.     ,   0.     ,   5.46875,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   4.6875 ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,  14.0625 ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
         0.     ,   0.     ,   0.     ,   0.     , 

In [581]:
a.shape
print a

print a.transpose()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [577]:
a = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [544]:
getCellIdxTerrainDistribution(0,100,False)

[(u'mountainRed', 50.78125),
 (u'bushGreen', 14.0625),
 (u'mountainGreen', 10.9375),
 (u'bushRed', 7.8125),
 (u'mountainWhite', 6.25),
 (u'waterRed', 5.46875),
 (u'waterGreen', 4.6875)]

In [550]:
print getDistribution(0)
marginal = np.zeros(len(Ctype))

for t,p in getDistribution(0):
    marginal[cTypeToIdx(t)] = p

print ipynb

[(u'mountainRed', 50.78125), (u'bushGreen', 14.0625), (u'mountainGreen', 10.9375), (u'bushRed', 7.8125), (u'mountainWhite', 6.25), (u'waterRed', 5.46875), (u'waterGreen', 4.6875)]
[  0.        0.       10.9375    0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.        6.25
   0.        0.        0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.        7.8125
   0.        0.        5.46875   0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.        0.
   0.        4.6875    0.        0.        0.        0.        0.        0.
   0.        0.       14.0625    0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.        0.
   0.        0.       50.78125   0.        0.        0

In [657]:
def printJsArray(matrix):
    
    
    jsStr = "["
    
    if isinstance(matrix, np.matrix) :
        matrix = np.asarray(matrix)
        for row in matrix:

            jsStr = jsStr + "["
            for col in row:
                
                jsStr = jsStr + str(col).rstrip() + ", "
            
            jsStr = jsStr[:-2]
            jsStr = jsStr + "],"
            
       
        
        
    elif isinstance(matrix, np.ndarray) :
       
        for row in matrix:
            jsStr = jsStr + "["
            for col in row:
                jsStr = jsStr + str(col).strip() + ", "
            
            jsStr = jsStr[:-2]
            jsStr = jsStr + "],"
            
       
    else:
       
        for i in matrix:
            jsStr = jsStr + str(i) + ","
            
    jsStr = jsStr[:-1]
    jsStr = jsStr + "]"
        
    return jsStr.replace('\n','')

In [649]:
cpd + ","

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

In [658]:
printJsArray(cpd)

'[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.999999999993,

In [562]:
cTypeToIdx("waterGreenTopRight")

43

In [566]:
printJsCType()

[ 'gateWhiteLeft', 'guardGreen', 'mountainGreen', 'waterGreenLower', 'guardWhite', 'rockRed', 'gateRedTop', 'mountainRedLowerLeft', 'waterRedOutsideLowerLeft', 'sandRedLeft', 'mountainRedLowerRight', 'waterRedLowerLeft', 'ladderWhite', 'gateWhiteTopLeft', 'gateWhiteCyclopsTop', 'mountainWhite', 'sand', 'sandRedLower', 'waterRedLowerRight', 'mountainGreenTop', 'mountainRedTopLeft', 'guardRed', 'sandRedLowerRight', 'gateGreenTop', 'gateRedTopRight', 'sandRedTopLeft', 'sandRedLowerLeft', 'gateGreenTopLeft', 'waterGreenLowerRight', 'dirtGrey', 'treeGreenRight', 'bushRed', 'waterRedLeft', 'dirt', 'waterRed', 'ladderGreen', 'water', 'waterGreenTopLeft', 'headstone', 'gateRedRight', 'waterRedLower', 'treeGreenTop', 'waterRedOutsideLowerRight', 'waterGreenTopRight', 'gateWhiteTop', 'ladderRed', 'treeRedRight', 'waterRedOutsideTopLeft', 'waterGreenOutsideTopRight', 'waterGreen', 'waterGreenRight', 'mountainGreenTopLeft', 'mountainWhiteTopRight', 'mountainGreenLowerRight', 'mountainGreenTopRight

In [565]:
def printJsCType():
    print "[",
    for i in Ctype:
        print  "'" + i + "',",
    print "]"

In [563]:
Ctype

[u'gateWhiteLeft',
 u'guardGreen',
 u'mountainGreen',
 u'waterGreenLower',
 u'guardWhite',
 u'rockRed',
 u'gateRedTop',
 u'mountainRedLowerLeft',
 u'waterRedOutsideLowerLeft',
 u'sandRedLeft',
 u'mountainRedLowerRight',
 u'waterRedLowerLeft',
 u'ladderWhite',
 u'gateWhiteTopLeft',
 u'gateWhiteCyclopsTop',
 u'mountainWhite',
 u'sand',
 u'sandRedLower',
 u'waterRedLowerRight',
 u'mountainGreenTop',
 u'mountainRedTopLeft',
 u'guardRed',
 u'sandRedLowerRight',
 u'gateGreenTop',
 u'gateRedTopRight',
 u'sandRedTopLeft',
 u'sandRedLowerLeft',
 u'gateGreenTopLeft',
 u'waterGreenLowerRight',
 u'dirtGrey',
 u'treeGreenRight',
 u'bushRed',
 u'waterRedLeft',
 u'dirt',
 u'waterRed',
 u'ladderGreen',
 u'water',
 u'waterGreenTopLeft',
 u'headstone',
 u'gateRedRight',
 u'waterRedLower',
 u'treeGreenTop',
 u'waterRedOutsideLowerRight',
 u'waterGreenTopRight',
 u'gateWhiteTop',
 u'ladderRed',
 u'treeRedRight',
 u'waterRedOutsideTopLeft',
 u'waterGreenOutsideTopRight',
 u'waterGreen',
 u'waterGreenRight'